#!/bin/sh
#

if [ -n "$GIT_AUTHOR_NAME" ]; then
	BRANCH=`git branch | grep '^\*' | cut -b3-`

	if ! grep -q '\[AUTHOR\]' $1 || grep -q '\[PATCH\]' $1; then
		echo "[AUTHOR] = $GIT_AUTHOR_NAME <$GIT_AUTHOR_EMAIL>" >> "$1"
	fi
	if ! grep -q '\[BRANCH\]' $1 || grep -q '\[PATCH\]' $1; then
		echo "[BRANCH] = $BRANCH" >> "$1"
	fi
fi

case "$2,$3" in  
	merge,)
		if grep -q Conflicts $1; then
			CONFLICT='[CONFLICTS]'
		else
			CONFLICT='[NO-CONFLICTS]'
		fi
		sed -i.bak -e "1s/^/[MERGE]$CONFLICT - /" $1 ;;
	*) ;;  
esac 